package top.longmarch;

import cn.hutool.core.thread.ThreadUtil;
import cn.hutool.http.HttpUtil;
import cn.hutool.json.JSONArray;
import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PostTest {


    public static void main(String[] args) {
        String url = "http://116.228.202.86:10052/match_drug_batch";
        JSONArray array = JSONUtil.parseArray(str);
        for (int i = 0; i < 20; i++) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    System.out.println(Thread.currentThread().getName());
                    String post = HttpUtil.post(url, array.toString());
                    System.out.println(post);
                }
            }).start();
        }
    }

    static String str = "[\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074200\",\n" +
            "        \"product_name\":\"吡嗪酰胺片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"250mg/片\",\n" +
            "        \"producer\":\"江苏江山制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074300\",\n" +
            "        \"product_name\":\"弥凝注射液(醋酸去氨加压素)*★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"4微克 1ml/支\",\n" +
            "        \"producer\":\"瑞典辉凌(瑞典)制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074201\",\n" +
            "        \"product_name\":\"吡嗪酰胺片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"250mgx100片/瓶\",\n" +
            "        \"producer\":\"江苏江山制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074301\",\n" +
            "        \"product_name\":\"弥凝注射液(醋酸去氨加压素)*★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"4微克 1mlx10支/\",\n" +
            "        \"producer\":\"瑞典辉凌(瑞典)制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074400\",\n" +
            "        \"product_name\":\"谷氨酸片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300mg/片\",\n" +
            "        \"producer\":\"常州制药厂有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074401\",\n" +
            "        \"product_name\":\"谷氨酸片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300mgx100片/瓶\",\n" +
            "        \"producer\":\"常州制药厂有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075000\",\n" +
            "        \"product_name\":\"多塞平片(盐酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"25mg/片\",\n" +
            "        \"producer\":\"上海黄河(制药厂)利亚制药有限公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074600\",\n" +
            "        \"product_name\":\"r-氨酪酸片als\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"250mg/片\",\n" +
            "        \"producer\":\"上海黄海制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074601\",\n" +
            "        \"product_name\":\"r-氨酪酸片als\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"250mgx100片/瓶\",\n" +
            "        \"producer\":\"上海黄海制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075101\",\n" +
            "        \"product_name\":\"定痉灵注射液(羟戊丁氨酯)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mlx5支/盒\",\n" +
            "        \"producer\":\"匈牙利CHINOIN制药化学有限\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074800\",\n" +
            "        \"product_name\":\"诺雷德长效植入剂(戈舍瑞林)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"3.6mg/支\",\n" +
            "        \"producer\":\"中国\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075001\",\n" +
            "        \"product_name\":\"多塞平片(盐酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"25mgx100片/瓶\",\n" +
            "        \"producer\":\"上海黄河(制药厂)利亚制药有限公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074900\",\n" +
            "        \"product_name\":\"奋乃静片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/片\",\n" +
            "        \"producer\":\"江苏南通第三制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074901\",\n" +
            "        \"product_name\":\"奋乃静片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx100片/瓶\",\n" +
            "        \"producer\":\"江苏南通第三制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075100\",\n" +
            "        \"product_name\":\"定痉灵注射液(羟戊丁氨酯)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2ml/支\",\n" +
            "        \"producer\":\"匈牙利CHINOIN制药化学有限\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075300\",\n" +
            "        \"product_name\":\"注射用格拉诺赛特(糖蛋白造血因\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50微克/瓶\",\n" +
            "        \"producer\":\"日本中外制药株式会社\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075401\",\n" +
            "        \"product_name\":\"息斯敏片(阿司咪唑)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mgx10片/盒\",\n" +
            "        \"producer\":\"西安杨森制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075400\",\n" +
            "        \"product_name\":\"息斯敏片(阿司咪唑)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mg/片\",\n" +
            "        \"producer\":\"西安杨森制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075600\",\n" +
            "        \"product_name\":\"扑尔敏片(马来酸氯苯那敏)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"4mg/片\",\n" +
            "        \"producer\":\"广西桂林制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075601\",\n" +
            "        \"product_name\":\"扑尔敏片(马来酸氯苯那敏)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"4mgx100片/瓶\",\n" +
            "        \"producer\":\"广西桂林制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075700\",\n" +
            "        \"product_name\":\"济得注射液(替硝唑氯化钠)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.4g 100ml/瓶\",\n" +
            "        \"producer\":\"湖北广济药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075800\",\n" +
            "        \"product_name\":\"碳酸锂片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"250mg/片\",\n" +
            "        \"producer\":\"湖南株洲千金药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075801\",\n" +
            "        \"product_name\":\"碳酸锂片t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"250mgx100片/瓶\",\n" +
            "        \"producer\":\"湖南株洲千金药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076001\",\n" +
            "        \"product_name\":\"参麦注射液\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 10mlx3支/盒\",\n" +
            "        \"producer\":\"正大青春宝药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00075900\",\n" +
            "        \"product_name\":\"易顺脉气雾剂(硝酸异山梨酯长效)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"17g 20ml/瓶\",\n" +
            "        \"producer\":\"德国马赫公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076000\",\n" +
            "        \"product_name\":\"参麦注射液\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 10ml/支\",\n" +
            "        \"producer\":\"正大青春宝药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076100\",\n" +
            "        \"product_name\":\"能全力口服液*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 500ml/瓶\",\n" +
            "        \"producer\":\"荷兰纽迪希亚公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076300\",\n" +
            "        \"product_name\":\"能全素粉*★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 430g/听\",\n" +
            "        \"producer\":\"荷兰纽迪希亚公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076600\",\n" +
            "        \"product_name\":\"钙尔奇D片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"600mg/片\",\n" +
            "        \"producer\":\"苏州姑苏制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076501\",\n" +
            "        \"product_name\":\"达先片(沙雷肽酶)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mgx30片/盒\",\n" +
            "        \"producer\":\"天津武田药品有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077001\",\n" +
            "        \"product_name\":\"里素劳片(酮康唑)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.2gx10片/盒\",\n" +
            "        \"producer\":\"西安杨森制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076601\",\n" +
            "        \"product_name\":\"钙尔奇D片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"600mgx30片/瓶\",\n" +
            "        \"producer\":\"苏州姑苏制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076901\",\n" +
            "        \"product_name\":\"苯苄胺片(酚苄明）\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mgx24片/瓶\",\n" +
            "        \"producer\":\"中国新疆伊梨制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077000\",\n" +
            "        \"product_name\":\"里素劳片(酮康唑)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.2g/片\",\n" +
            "        \"producer\":\"西安杨森制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076500\",\n" +
            "        \"product_name\":\"达先片(沙雷肽酶)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mg/片\",\n" +
            "        \"producer\":\"天津武田药品有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077100\",\n" +
            "        \"product_name\":\"高特灵片(盐酸特拉唑嗪)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/片\",\n" +
            "        \"producer\":\"英国雅培药厂(美国雅培制药公司)\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076800\",\n" +
            "        \"product_name\":\"三乐喜胶囊(阿尼西坦)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.1g/粒\",\n" +
            "        \"producer\":\"江苏无锡艾西恩制药有限公司(第四\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077101\",\n" +
            "        \"product_name\":\"高特灵片(盐酸特拉唑嗪)t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx28片/盒\",\n" +
            "        \"producer\":\"英国雅培药厂(美国雅培制药公司)\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077200\",\n" +
            "        \"product_name\":\"甲磺酸二氢麦角碱缓释胶囊(培磊\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2.5mg/粒\",\n" +
            "        \"producer\":\"赛诺菲安万特(杭州)制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077300\",\n" +
            "        \"product_name\":\"糖适平片(格列喹酮)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"30mg/片\",\n" +
            "        \"producer\":\"北京万辉双鹤药业有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076900\",\n" +
            "        \"product_name\":\"苯苄胺片(酚苄明）\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mg/片\",\n" +
            "        \"producer\":\"中国沈阳协合制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077201\",\n" +
            "        \"product_name\":\"甲磺酸二氢麦角碱缓释胶囊(培磊\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2.5mgx30粒/盒\",\n" +
            "        \"producer\":\"赛诺菲安万特(杭州)制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00076801\",\n" +
            "        \"product_name\":\"三乐喜胶囊(阿尼西坦)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.1gx30粒/瓶\",\n" +
            "        \"producer\":\"江苏无锡艾西恩制药有限公司(第四\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077202\",\n" +
            "        \"product_name\":\"甲磺酸二氢麦角碱缓释胶囊(培磊\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2.5mg x10粒/板\",\n" +
            "        \"producer\":\"赛诺菲安万特(杭州)制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077500\",\n" +
            "        \"product_name\":\"膀胱灵胶囊*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO /粒\",\n" +
            "        \"producer\":\"德国飞英克药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077401\",\n" +
            "        \"product_name\":\"太得恩胶囊（通尿灵）\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 50mgx10粒/盒\",\n" +
            "        \"producer\":\"法国利博福尼制药公司\",\n" +
            "        \"registerNo\":\"进Z20050027\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077400\",\n" +
            "        \"product_name\":\"太得恩胶囊（通尿灵）\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 50mg/粒\",\n" +
            "        \"producer\":\"法国利博福尼制药公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077501\",\n" +
            "        \"product_name\":\"膀胱灵胶囊*t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 30粒/瓶\",\n" +
            "        \"producer\":\"德国飞英克药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077301\",\n" +
            "        \"product_name\":\"糖适平片(格列喹酮)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"30mgx60片/瓶\",\n" +
            "        \"producer\":\"北京万辉双鹤药业有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077900\",\n" +
            "        \"product_name\":\"丽珠得乐胶囊(枸橼酸铋钾)t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"110mg/粒\",\n" +
            "        \"producer\":\"丽珠集团丽珠制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078000\",\n" +
            "        \"product_name\":\"胃复安片(甲氧氯普胺)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mg/片\",\n" +
            "        \"producer\":\"常熟市星海制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078100\",\n" +
            "        \"product_name\":\"得舒特片(匹维溴铵)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50mg/片\",\n" +
            "        \"producer\":\"法国苏威制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073200\",\n" +
            "        \"product_name\":\"葡萄糖酸钙片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"500mg/片\",\n" +
            "        \"producer\":\"北京双鹤药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00077901\",\n" +
            "        \"product_name\":\"丽珠得乐胶囊(枸橼酸铋钾)t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"110mgx40粒/盒\",\n" +
            "        \"producer\":\"丽珠集团丽珠制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078001\",\n" +
            "        \"product_name\":\"胃复安片(甲氧氯普胺)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mgx100片/瓶\",\n" +
            "        \"producer\":\"江苏常熟卫生用品厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073201\",\n" +
            "        \"product_name\":\"葡萄糖酸钙片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"500mgx100片/瓶\",\n" +
            "        \"producer\":\"北京双鹤药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078200\",\n" +
            "        \"product_name\":\"丽珠肠乐胶囊(双歧杆菌活菌)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO /粒\",\n" +
            "        \"producer\":\"丽珠集团丽珠制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073400\",\n" +
            "        \"product_name\":\"弥可保注射液(钴宾酰胺)★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"500微克 1ml/支\",\n" +
            "        \"producer\":\"辽宁沈阳卫材制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078101\",\n" +
            "        \"product_name\":\"得舒特片(匹维溴铵)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50mgx30片/盒\",\n" +
            "        \"producer\":\"法国苏威制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073401\",\n" +
            "        \"product_name\":\"弥可保注射液(钴宾酰胺)★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"500微克 1mlx10支\",\n" +
            "        \"producer\":\"辽宁沈阳卫材制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078201\",\n" +
            "        \"product_name\":\"丽珠肠乐胶囊t(双歧杆菌活菌)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 10粒/盒\",\n" +
            "        \"producer\":\"丽珠集团丽珠制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078400\",\n" +
            "        \"product_name\":\"替勃龙片(利维爱)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2.5mg/片\",\n" +
            "        \"producer\":\"南京欧加农制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078401\",\n" +
            "        \"product_name\":\"替勃龙片(利维爱)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2.5mgx7片/盒\",\n" +
            "        \"producer\":\"南京欧加农制药有限公司\",\n" +
            "        \"registerNo\":\"国H20051085\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073600\",\n" +
            "        \"product_name\":\"丙基硫氧嘧啶片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50mg/片\",\n" +
            "        \"producer\":\"南通精华制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078500\",\n" +
            "        \"product_name\":\"阿莫仙胶囊(阿莫西林)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.25g/粒\",\n" +
            "        \"producer\":\"珠海联邦制药股份有限公司中山分公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073601\",\n" +
            "        \"product_name\":\"丙基硫氧嘧啶片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50mgx100片/瓶\",\n" +
            "        \"producer\":\"南通精华制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078501\",\n" +
            "        \"product_name\":\"阿莫仙胶囊(阿莫西林)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.25gx24粒/盒\",\n" +
            "        \"producer\":\"珠海联邦制药股份有限公司中山分公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073700\",\n" +
            "        \"product_name\":\"益康升血肽注射液*★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 2ml/支\",\n" +
            "        \"producer\":\"贵州益康制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078600\",\n" +
            "        \"product_name\":\"希刻劳胶囊(头孢克罗)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.25g/粒\",\n" +
            "        \"producer\":\"苏州第三制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073800\",\n" +
            "        \"product_name\":\"伯氨喹啉片(磷酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"13.2mg/片\",\n" +
            "        \"producer\":\"上海天平制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078601\",\n" +
            "        \"product_name\":\"希刻劳胶囊(头孢克罗)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.25gx12粒/盒\",\n" +
            "        \"producer\":\"苏州第三制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073701\",\n" +
            "        \"product_name\":\"益康升血肽注射液*★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 2mlx5支/盒\",\n" +
            "        \"producer\":\"贵州益康制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078800\",\n" +
            "        \"product_name\":\"斯皮仁诺胶囊(伊曲康唑)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mg/粒\",\n" +
            "        \"producer\":\"西安杨森制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074000\",\n" +
            "        \"product_name\":\"特斯乐注射液(抑肽酶)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"70mg 50ml/瓶\",\n" +
            "        \"producer\":\"拜耳医药保健有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078901\",\n" +
            "        \"product_name\":\"心达康片(醋柳黄酮)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mgx60片/盒\",\n" +
            "        \"producer\":\"四川美大康药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00073801\",\n" +
            "        \"product_name\":\"伯氨喹啉片(磷酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"13.2mgx1000片/瓶\",\n" +
            "        \"producer\":\"上海天平制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078801\",\n" +
            "        \"product_name\":\"斯皮仁诺胶囊(伊曲康唑)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mgx14粒/盒\",\n" +
            "        \"producer\":\"西安杨森制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074101\",\n" +
            "        \"product_name\":\"异烟肼片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mgx100片/瓶\",\n" +
            "        \"producer\":\"江苏\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00079000\",\n" +
            "        \"product_name\":\"特茉芬片(枸橼酸他莫昔芬)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mg/片\",\n" +
            "        \"producer\":\"芬兰利拉斯药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00074100\",\n" +
            "        \"product_name\":\"异烟肼片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mg/片\",\n" +
            "        \"producer\":\"加拿大先灵葆雅药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00078900\",\n" +
            "        \"product_name\":\"心达康片(醋柳黄酮)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mg/片\",\n" +
            "        \"producer\":\"四川美大康药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00063400\",\n" +
            "        \"product_name\":\"佳苏仑注射液(盐酸多沙普仑)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mg 5ml/支\",\n" +
            "        \"producer\":\"江苏恩华药业股份有限公司\",\n" +
            "        \"registerNo\":\"国H32022989\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069101\",\n" +
            "        \"product_name\":\"甲状腺片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"40mgx100片/瓶\",\n" +
            "        \"producer\":\"浙江金华生物化学制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00063700\",\n" +
            "        \"product_name\":\"注射用思他宁(施他宁/生长抑素)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.25mg/支\",\n" +
            "        \"producer\":\"瑞士素高大药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069000\",\n" +
            "        \"product_name\":\"消炎利胆片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO /片\",\n" +
            "        \"producer\":\"广东汕头制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00063801\",\n" +
            "        \"product_name\":\"甘草甜素片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"75mgx30片/瓶\",\n" +
            "        \"producer\":\"湖南长沙九芝堂制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069200\",\n" +
            "        \"product_name\":\"诺维苯注射液(异长春花碱)*★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mg 1ml/支\",\n" +
            "        \"producer\":\"法国皮尔-法伯大药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064000\",\n" +
            "        \"product_name\":\"尼达尔片(尼莫地平)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mg/片\",\n" +
            "        \"producer\":\"天津市中央药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069301\",\n" +
            "        \"product_name\":\"安易醒注射液(氟吗西尼)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.5mg 5mlx5支/盒\",\n" +
            "        \"producer\":\"瑞士(巴塞尔豪夫迈/曼.)罗氏有\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069300\",\n" +
            "        \"product_name\":\"安易醒注射液(氟吗西尼)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.5mg 5ml/支\",\n" +
            "        \"producer\":\"瑞士(巴塞尔豪夫迈/曼.)罗氏有\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064001\",\n" +
            "        \"product_name\":\"尼达尔片(尼莫地平)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mgx50片/瓶\",\n" +
            "        \"producer\":\"天津市中央药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069501\",\n" +
            "        \"product_name\":\"甲羟孕酮片(安宫黄体酮)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx100片/瓶\",\n" +
            "        \"producer\":\"浙江仙琚制药股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064101\",\n" +
            "        \"product_name\":\"维铁缓释片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 7片/盒\",\n" +
            "        \"producer\":\"广州迈特兴华制药厂有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069500\",\n" +
            "        \"product_name\":\"甲羟孕酮片(安宫黄体酮)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/片\",\n" +
            "        \"producer\":\"浙江仙琚制药股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00063800\",\n" +
            "        \"product_name\":\"甘草甜素片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"75mg/片\",\n" +
            "        \"producer\":\"湖南长沙九芝堂制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069700\",\n" +
            "        \"product_name\":\"欧乃派克注射液(碘海醇)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50ml/瓶\",\n" +
            "        \"producer\":\"纽迪希亚制药(无锡)有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064100\",\n" +
            "        \"product_name\":\"维铁缓释片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO /片\",\n" +
            "        \"producer\":\"广州迈特兴华制药厂有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069600\",\n" +
            "        \"product_name\":\"氟吗西尼注射液*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.5mg 5ml/支\",\n" +
            "        \"producer\":\"浙江奥托康制药集团股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064601\",\n" +
            "        \"product_name\":\"斯托芬注射液(甲磺酸氢化麦角碱*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.3mg 1mlx10支/\",\n" +
            "        \"producer\":\"斯洛文尼亚LEK AND D.D\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064600\",\n" +
            "        \"product_name\":\"斯托芬注射液(甲磺酸氢化麦角碱*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.3mg 1ml/支\",\n" +
            "        \"producer\":\"斯洛文尼亚LEK AND D.D\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069901\",\n" +
            "        \"product_name\":\"易善复注射液(肝得健)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mlx5支/盒\",\n" +
            "        \"producer\":\"德国礼来制药公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064400\",\n" +
            "        \"product_name\":\"注射用噻吗灵(拉氧头孢钠)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"1g/瓶\",\n" +
            "        \"producer\":\"海南省海灵制药厂\",\n" +
            "        \"registerNo\":\"国H10930104\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070001\",\n" +
            "        \"product_name\":\"易善复胶囊(肝得健)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300mgx24粒/盒\",\n" +
            "        \"producer\":\"丹阳市药业有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00064800\",\n" +
            "        \"product_name\":\"诺和笔3*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"/支\",\n" +
            "        \"producer\":\"中国\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069900\",\n" +
            "        \"product_name\":\"易善复注射液(肝得健)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5ml/支\",\n" +
            "        \"producer\":\"德国礼来制药公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065000\",\n" +
            "        \"product_name\":\"华法林钠片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"3mg/片\",\n" +
            "        \"producer\":\"芬兰欧加农制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070000\",\n" +
            "        \"product_name\":\"易善复胶囊(肝得健)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300mg/粒\",\n" +
            "        \"producer\":\"丹阳市药业有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065001\",\n" +
            "        \"product_name\":\"华法林钠片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"3mgx100片/瓶\",\n" +
            "        \"producer\":\"芬兰欧加农制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070200\",\n" +
            "        \"product_name\":\"金葡液注射液(骨折愈合刺激素)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"400单位 2ml/支\",\n" +
            "        \"producer\":\"吉林长春高斯达生化药业股份有限公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065300\",\n" +
            "        \"product_name\":\"华法林钠片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mg/片\",\n" +
            "        \"producer\":\"芬兰欧加农制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070300\",\n" +
            "        \"product_name\":\"己烯雌酚片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"1mg/片\",\n" +
            "        \"producer\":\"上海利生制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065301\",\n" +
            "        \"product_name\":\"华法林钠片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mgx100片/瓶\",\n" +
            "        \"producer\":\"芬兰欧加农制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070201\",\n" +
            "        \"product_name\":\"金葡液注射液(骨折愈合刺激素)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"400单位 2mlx5支/\",\n" +
            "        \"producer\":\"吉林长春高斯达生化药业股份有限公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065700\",\n" +
            "        \"product_name\":\"活性钙颗粒*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5g/袋\",\n" +
            "        \"producer\":\"广州光华药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070301\",\n" +
            "        \"product_name\":\"己烯雌酚片t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"1mgx100片/瓶\",\n" +
            "        \"producer\":\"上海利生制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065800\",\n" +
            "        \"product_name\":\"保尔佳注射液*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"30微克 1ml/支\",\n" +
            "        \"producer\":\"德国HOR-FER-VIT PH\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070600\",\n" +
            "        \"product_name\":\"速避凝注射液(低分子肝素钙)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.3mg 0.4ml/支\",\n" +
            "        \"producer\":\"浙江杭州龙德医用器械有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065701\",\n" +
            "        \"product_name\":\"活性钙颗粒*t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5gx20袋/包\",\n" +
            "        \"producer\":\"广州光华药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070701\",\n" +
            "        \"product_name\":\"呋喃硫胺片(盐酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"25mgx100片/瓶\",\n" +
            "        \"producer\":\"江苏鹏鹞药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065900\",\n" +
            "        \"product_name\":\"注射用高舒达(法莫替丁)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mg/支\",\n" +
            "        \"producer\":\"安斯泰来制药(中国)有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070700\",\n" +
            "        \"product_name\":\"呋喃硫胺片(盐酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"25mg/片\",\n" +
            "        \"producer\":\"江苏鹏鹞药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065801\",\n" +
            "        \"product_name\":\"保尔佳注射液*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"30微克 1mlx10支/\",\n" +
            "        \"producer\":\"德国HOR-FER-VIT PH\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070801\",\n" +
            "        \"product_name\":\"注射用七叶皂甙钠\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mgx8支/盒\",\n" +
            "        \"producer\":\"山东绿叶制药股份有限公司\",\n" +
            "        \"registerNo\":\"国H20003239\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066001\",\n" +
            "        \"product_name\":\"多烯酸乙酯胶丸\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"450mgx60粒/盒\",\n" +
            "        \"producer\":\"浙江得恩德制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070901\",\n" +
            "        \"product_name\":\"脑复康注射液(乙酰胺吡咯烷酮)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"1g 5mlx10支/盒\",\n" +
            "        \"producer\":\"天津大通红日制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066100\",\n" +
            "        \"product_name\":\"大蒜素注射液\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"30mg 2ml/支\",\n" +
            "        \"producer\":\"上海禾丰制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071000\",\n" +
            "        \"product_name\":\"维生素B1片(盐酸硫胺)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mg/片\",\n" +
            "        \"producer\":\"上海黄河(制药厂)利亚制药有限公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066000\",\n" +
            "        \"product_name\":\"多烯酸乙酯胶丸\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"450mg/粒\",\n" +
            "        \"producer\":\"浙江得恩德制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070900\",\n" +
            "        \"product_name\":\"脑复康注射液(乙酰胺吡咯烷酮)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"1g 5ml/支\",\n" +
            "        \"producer\":\"天津大通红日制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00065901\",\n" +
            "        \"product_name\":\"注射用高舒达(法莫替丁)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mgx10支/盒\",\n" +
            "        \"producer\":\"安斯泰来制药(中国)有限公司\",\n" +
            "        \"registerNo\":\"J20060006\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071001\",\n" +
            "        \"product_name\":\"维生素B1片(盐酸硫胺)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mgx4000片/盒\",\n" +
            "        \"producer\":\"上海黄河(制药厂)利亚制药有限公\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066101\",\n" +
            "        \"product_name\":\"大蒜素注射液\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"30mg 2mlx5支/盒\",\n" +
            "        \"producer\":\"上海禾丰制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071101\",\n" +
            "        \"product_name\":\"维生素A胶丸\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2.5万单位x100粒/\",\n" +
            "        \"producer\":\"厦门星鲨制药有限公司\",\n" +
            "        \"registerNo\":\"国H35020246\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00070800\",\n" +
            "        \"product_name\":\"注射用七叶皂甙钠\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mg/支\",\n" +
            "        \"producer\":\"山东绿叶制药股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066601\",\n" +
            "        \"product_name\":\"注射用抗胃腺癌免疫核糖核酸t*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx5支/盒\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071200\",\n" +
            "        \"product_name\":\"维生素E胶丸(生育酚)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mg/粒\",\n" +
            "        \"producer\":\"厦门鱼肝油厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066700\",\n" +
            "        \"product_name\":\"利福平胶囊\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"150mg/粒\",\n" +
            "        \"producer\":\"黑龙江哈尔滨制药四厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071100\",\n" +
            "        \"product_name\":\"维生素A胶丸\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2.5万单位/粒\",\n" +
            "        \"producer\":\"厦门星鲨制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066600\",\n" +
            "        \"product_name\":\"注射用抗胃腺癌免疫核糖核酸*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/支\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071201\",\n" +
            "        \"product_name\":\"维生素E胶丸(生育酚)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mgx30粒/盒\",\n" +
            "        \"producer\":\"厦门鱼肝油厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066801\",\n" +
            "        \"product_name\":\"注射用抗肺癌免疫核糖核酸t*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx5支/盒\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071400\",\n" +
            "        \"product_name\":\"维生素E胶丸(生育酚)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mg/粒\",\n" +
            "        \"producer\":\"厦门鱼肝油厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066701\",\n" +
            "        \"product_name\":\"利福平胶囊\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"150mgx100粒/瓶\",\n" +
            "        \"producer\":\"黑龙江哈尔滨制药四厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071401\",\n" +
            "        \"product_name\":\"维生素E胶丸(生育酚)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"10mgx100粒/瓶\",\n" +
            "        \"producer\":\"厦门鱼肝油厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066800\",\n" +
            "        \"product_name\":\"注射用抗肺癌免疫核糖核酸*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/支\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071501\",\n" +
            "        \"product_name\":\"美斯纳注射液(巯乙磺酸钠)★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.4g 4mlx15支/盒\",\n" +
            "        \"producer\":\"德国ASTA PHARMA AG\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071500\",\n" +
            "        \"product_name\":\"美斯纳注射液(巯乙磺酸钠)★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.4g 4ml/支\",\n" +
            "        \"producer\":\"德国ASTA PHARMA AG\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066901\",\n" +
            "        \"product_name\":\"注射用抗肠腺癌免疫核糖核酸t*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx5支/盒\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071600\",\n" +
            "        \"product_name\":\"烟酸片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mg/片\",\n" +
            "        \"producer\":\"牡丹江友搏药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067001\",\n" +
            "        \"product_name\":\"注射用抗肝细胞癌免疫核糖核酸*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx5支/盒\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00066900\",\n" +
            "        \"product_name\":\"注射用抗肠腺癌免疫核糖核酸*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/支\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071700\",\n" +
            "        \"product_name\":\"注射用匹服平(异环磷酰胺)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"1g/瓶\",\n" +
            "        \"producer\":\"江苏恒瑞医药股份有限公司\",\n" +
            "        \"registerNo\":\"国H10950292\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067000\",\n" +
            "        \"product_name\":\"注射用抗肝细胞癌免疫核糖核酸*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/支\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00071601\",\n" +
            "        \"product_name\":\"烟酸片t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mgx100片/瓶\",\n" +
            "        \"producer\":\"牡丹江友搏药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067101\",\n" +
            "        \"product_name\":\"注射用抗乳腺癌免疫核糖核酸*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mgx5支/盒\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072301\",\n" +
            "        \"product_name\":\"多酶片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 100片/瓶\",\n" +
            "        \"producer\":\"浙江嘉兴生物化学制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067100\",\n" +
            "        \"product_name\":\"注射用抗乳腺癌免疫核糖核酸*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"2mg/支\",\n" +
            "        \"producer\":\"长春海王生物制药有限责任公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072300\",\n" +
            "        \"product_name\":\"多酶片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO /片\",\n" +
            "        \"producer\":\"浙江嘉兴生物化学制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067200\",\n" +
            "        \"product_name\":\"复方磺胺甲基异恶唑片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.48g/片\",\n" +
            "        \"producer\":\"金陵药业股份有限公司南京金陵制药\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072500\",\n" +
            "        \"product_name\":\"肌苷片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"200mg/片\",\n" +
            "        \"producer\":\"上海天平制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067300\",\n" +
            "        \"product_name\":\"先特能(人粒-巨嗜C集落刺激因子\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50微克/瓶\",\n" +
            "        \"producer\":\"爱尔兰先灵葆雅制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072501\",\n" +
            "        \"product_name\":\"肌苷片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"200mgx100片/瓶\",\n" +
            "        \"producer\":\"上海天平制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067201\",\n" +
            "        \"product_name\":\"复方磺胺甲基异恶唑片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"0.48gx24片/盒\",\n" +
            "        \"producer\":\"金陵药业股份有限公司南京金陵制药\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072701\",\n" +
            "        \"product_name\":\"甘泰片(阿昔洛韦)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mgx24片/盒\",\n" +
            "        \"producer\":\"湖北康纳制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067400\",\n" +
            "        \"product_name\":\"先特能(人粒-巨嗜C集落刺激因子*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"150微克/瓶\",\n" +
            "        \"producer\":\"爱尔兰先灵葆雅制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072801\",\n" +
            "        \"product_name\":\"泛酸钙片t*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mgx100片/瓶\",\n" +
            "        \"producer\":\"天津金耀氨基酸有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067500\",\n" +
            "        \"product_name\":\"先特能(人粒-巨嗜C集落刺激因子*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300微克/瓶\",\n" +
            "        \"producer\":\"爱尔兰先灵葆雅制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072700\",\n" +
            "        \"product_name\":\"甘泰片(阿昔洛韦)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mg/片\",\n" +
            "        \"producer\":\"湖北康纳制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072800\",\n" +
            "        \"product_name\":\"泛酸钙片*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mg/片\",\n" +
            "        \"producer\":\"天津金耀氨基酸有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072901\",\n" +
            "        \"product_name\":\"羟基脲片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"500mgx100片/瓶\",\n" +
            "        \"producer\":\"山东绿叶制药股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067900\",\n" +
            "        \"product_name\":\"依膦片(羟乙膦酸钠)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"200mg/片\",\n" +
            "        \"producer\":\"江苏联环药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00072900\",\n" +
            "        \"product_name\":\"羟基脲片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"500mg/片\",\n" +
            "        \"producer\":\"山东绿叶制药股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068000\",\n" +
            "        \"product_name\":\"新速效感冒片*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO /片\",\n" +
            "        \"producer\":\"北京双鹤药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068001\",\n" +
            "        \"product_name\":\"新速效感冒片*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 12片/盒\",\n" +
            "        \"producer\":\"北京双鹤药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067700\",\n" +
            "        \"product_name\":\"必可酮气雾剂(丙酸倍氯米松)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"200d 50微克/瓶\",\n" +
            "        \"producer\":\"中外合资宜昌民康药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067800\",\n" +
            "        \"product_name\":\"必可酮气雾剂(丙酸倍氯米松)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"200d 250微克/瓶\",\n" +
            "        \"producer\":\"中外合资宜昌民康药业有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00067901\",\n" +
            "        \"product_name\":\"依膦片t(羟乙膦酸钠)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"200mgx10片/盒\",\n" +
            "        \"producer\":\"江苏联环药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068201\",\n" +
            "        \"product_name\":\"吡罗昔康片t(炎痛喜康)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mgx50片/瓶\",\n" +
            "        \"producer\":\"江苏济川制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068400\",\n" +
            "        \"product_name\":\"吗啉咪胍片(盐酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mg/片\",\n" +
            "        \"producer\":\"江苏金坛红光医疗器械厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068700\",\n" +
            "        \"product_name\":\"阿斯匹林肠溶片(乙酰水杨酸)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300mg/片\",\n" +
            "        \"producer\":\"金陵药业股份有限公司南京金陵制药\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068200\",\n" +
            "        \"product_name\":\"吡罗昔康片(炎痛喜康)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mg/片\",\n" +
            "        \"producer\":\"江苏济川制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068701\",\n" +
            "        \"product_name\":\"阿斯匹林肠溶片(乙酰水杨酸)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300mgx100片/瓶\",\n" +
            "        \"producer\":\"金陵药业股份有限公司南京金陵制药\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068800\",\n" +
            "        \"product_name\":\"吲哚美辛肠溶片(消炎痛)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"25mg/片\",\n" +
            "        \"producer\":\"江苏联环药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068801\",\n" +
            "        \"product_name\":\"吲哚美辛肠溶片(消炎痛)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"25mgx100片/瓶\",\n" +
            "        \"producer\":\"江苏联环药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068900\",\n" +
            "        \"product_name\":\"凯特瑞注射液(盐酸格拉司琼)★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"3mg 3ml/支\",\n" +
            "        \"producer\":\"F.Hoffmann-La Roche Ltd\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068901\",\n" +
            "        \"product_name\":\"凯特瑞注射液(盐酸格拉司琼)★\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"3mg 3mlx5支/盒\",\n" +
            "        \"producer\":\"F.Hoffmann-La Roche Ltd\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00068401\",\n" +
            "        \"product_name\":\"吗啉咪胍片(盐酸盐)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"100mgx100片/瓶\",\n" +
            "        \"producer\":\"江苏金坛红光医疗器械厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069001\",\n" +
            "        \"product_name\":\"消炎利胆片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 100片/瓶\",\n" +
            "        \"producer\":\"广东汕头制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00063500\",\n" +
            "        \"product_name\":\"惠福仁注射液(a-n1干扰素)*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"300万单位/瓶\",\n" +
            "        \"producer\":\"英国葛兰素威康集团(大药厂)\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00069100\",\n" +
            "        \"product_name\":\"甲状腺片\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"40mg/片\",\n" +
            "        \"producer\":\"浙江金华生物化学制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00061901\",\n" +
            "        \"product_name\":\"降压乐片(复方地舍平)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"CO 48片/盒\",\n" +
            "        \"producer\":\"黑龙江哈尔滨制药四厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062000\",\n" +
            "        \"product_name\":\"注射用去甲万古霉素\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"40万单位/瓶\",\n" +
            "        \"producer\":\"张家口市长城制药厂\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062100\",\n" +
            "        \"product_name\":\"注射用稳可信(盐酸万古霉素)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"500mg/瓶\",\n" +
            "        \"producer\":\"美国礼来亚洲公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062201\",\n" +
            "        \"product_name\":\"替加氟片(喃氟啶)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50mgx100片/瓶\",\n" +
            "        \"producer\":\"山东绿叶制药股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062200\",\n" +
            "        \"product_name\":\"替加氟片(喃氟啶)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"50mg/片\",\n" +
            "        \"producer\":\"山东绿叶制药股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062500\",\n" +
            "        \"product_name\":\"华蟾素注射液\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5ml/支\",\n" +
            "        \"producer\":\"安徽华润金蟾药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062501\",\n" +
            "        \"product_name\":\"华蟾素注射液t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"5mlx10支/盒\",\n" +
            "        \"producer\":\"安徽华润金蟾药业股份有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062600\",\n" +
            "        \"product_name\":\"治胃灵片*\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mg/片\",\n" +
            "        \"producer\":\"昆明积大制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"00062601\",\n" +
            "        \"product_name\":\"治胃灵片*t\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mgx50片/盒\",\n" +
            "        \"producer\":\"昆明积大制药有限公司\",\n" +
            "        \"registerNo\":\"\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"hospital_id\":\"000640\",\n" +
            "        \"product_name\":\"尼莫地平片(尼达尔)\",\n" +
            "        \"dosage_form\":\"\",\n" +
            "        \"spec\":\"20mg/片\",\n" +
            "        \"producer\":\"\",\n" +
            "        \"registerNo\":\"国H10910040\"\n" +
            "    }\n" +
            "]";
}
